[package]
name = "gtly"
version = "0.0.1"
authors = ["LNSEAB <691752+LNSEAB@users.noreply.github.com>"]
edition = "2018"
license = "Zlib"

[dependencies]
num = "0.4.0"
serde = { version = "1.0.125", optional = true, features = ["derive"] }
